### ISSUE TITLE
Potential issues with Camera values - not using tenths of scene unit

### ISSUE THREAD

**Issue by jessey-git** [erich666/McUsd#3]
Per the following in the USD spec, the Camera should be defined in "1/10th" units, because USD is just... wonderful :)

https://graphics.pixar.com/usd/release/api/class_usd_geom_camera.html#UsdGeom_CameraUnits
```
...
We do make a concession, however, in that lens and filmback properties are measured in tenths of a scene unit rather
than "raw" scene units. This means that with the fallback value of .01 for metersPerUnit - i.e. scene unit of
centimeters - then these "tenth of scene unit" properties are effectively millimeters.
```

I believe this means that the current camera values are 100x too big due to the used `metersPerUnit = 1`

Things might "look" ok because the ratio between the values is similarly off, but as more apps start respecting that part of the spec, the actual values are going to be very strange. Blender's importer will soon start using 1/10th, and after that fix the McUsd.usda model will load with a `focalLength` of 1.8 meters instead of 18mm for the camera which is hilarious :)

**Comment by erich666** [comment]
Thanks for the tip-off! And I'm a bit annoyed that Github didn't inform me this issue was filed. :(

Hmmm, what do you think is the right answer? The "easy" thing would be to just not set the metersPerUnit at all and let it default to 0.01, centimeters. But if there's a right way to set the camera values, that would be good to know. The whole "concession" stuff sounds a bit broken. I'm not quite sure where to go with this...

**Comment by jessey-git** [comment]
@erich666 Thanks for getting back, and yeah I have the same issue with github on occasion. I'm not sure what triggers the notifications.

Based on the blurb of text in that "spec", and from the ongoing conversation that started on usd-interest today (might be your friends? :) https://groups.google.com/g/usd-interest/c/Oc_YeqVvtbA), it seems like the way to go is to have these values properly scaled in the file so that DCCs can have the correct values when loading I think.  It's a useful test case so maybe keep `metersPerUnit=1` instead of the default 0.01.

Ultimately this is about how to triage incoming issues from user bug reports. If the spec stays as-is, and a report comes in saying "Blender imported the file wrong! Look the camera has a 1.8meter focal length." we're going to push back and tell whoever filed the issue to instead file the bug on the upstream DCC package that produced the "wrong" file - and we're probably not going to add another option to the import/export process to mitigate the shortcoming. Likewise for the reverse export process we'll try to write out good files and won't field reports that values "seem wrong" when imported to Houdini etc.

For example, assuming your file originally came from software-x, I'm going to ask you to please file the bug on that software because it seems to be producing "bad" files :)

And similarly, if you notice any software with a camera focal length that's incorrect, please file bugs on them too if possible lol. If USD is going to be a foundational technology the foundation should be solid without unnecessary quirks and a broken ecosystem of example files floating around. Especially this early on. The camera shouldn't just "look" right in the render, it should actually have the correct values still.

Rant over.  This isn't your fault btw :) This is exactly the type of thing your work should help to uncover, so thank you!

**Comment by erich666** [comment]
Thanks for the full reply! (And of course Github didn't tell me...)

Trying to fix things today, I had some elaborate scheme of changing a lot of numbers, scaling, etc. But then I just changed metersPerUnit to 0.01 (its default) and things seemed to be fine in usdview and Omniverse Create. I'm really not trying to test "what happens if everything is made meters," so this seemed like a better way to go.

I was actually pretty surprised this worked. Does this make sense to you? I'm happy for any other changes you might see that would be appropriate. I haven't folded it in here (yet), as the PR I'm submitting is more important. See https://github.com/usd-wg/assets/pull/25 for the current model's settings, etc. I'll also ask one USD camera expert I know to give it a sanity check.

**Comment by jessey-git** [comment]
Right, setting it back to 0.01 (cm) will work for the camera.  1/10th of cm's are mm, so therefore the camera focalLength of 18.147562 is in mm.  However, that means all your geometry is now in cm instead of meters too, so loading into a app that properly supports the metersPerUnit value will show (or should show) all the minecraft blocks as 1cm cubes instead of 1m cubes.

**Comment by erich666** [comment]
I can certainly live with that. The cubes in this test are no longer Minecraft cubes (it's not the point of the test), so them being 1 cm is fine.

So, good, I think I can check that test off the list. I'll rejigger the McUsd test itself this next week - I've just started to do so (Omniverse Create just changed, so I'm changing emissive surfaces to be more in keeping with their new interpretation and with common practice, in lieu of [an exacting spec on emissiveColor](https://github.com/erich666/McUsd#physical-units-for-lights)). Expect me to ping you again then to give it a look, if you would be so kind.

For scale, I'll probably just go the route of metersPerUnit = 0.01 there, too, and then scale up the whole scene to meters via:

```
def Xform "_Simple_Material_Test"
{
        double3 xformOp:scale = (100, 100, 100)
        uniform token[] xformOpOrder = ["xformOp:scale"]
```
        
near the top of the file, i.e., [here](https://github.com/erich666/McUsd/blob/main/model/McUsd.usda#L87). Anything I should know about that? Doing this will scale up the cubes and the two lights, but those lights are "at infinity" so that shouldn't matter. But if there's a better way to do this or structure the data, I'm all ears - this is the time to fix it nicely.

Thanks very much for your help so far!

**Comment by erich666** [comment]
Ping on this one, @jessey-git - may I close this one?

**Comment by jessey-git** [comment]
I was waiting to see the change checked in before closing :)  I think that's fine to do for a valid file.  So set metersPerUnit to 0.01 and later scale up if desired.

**Comment by erich666** [comment]
OK, I've updated McUsd in a bunch of ways, including not changing metersPerUnit from 0.01. See the branch https://github.com/erich666/McUsd/tree/usdwga/full_assets/McUsd - once I get feedback from you (so I can close this issue) and others, and then make the USDZ versions of the USDA files, I'll submit this McUsd to the USD Working Group Assets repo.

**Comment by jessey-git** [comment]
Seems ok!

**Comment by erich666** [comment]
Thanks! Closed.
